### ISSUE TITLE
Voronoi Preview cause crash in 4.0| not automatically create socket | Strange bug of Voronoi Repeating.

### ISSUE THREAD

**Issue by yunkezengren** [ugorek000/VoronoiLinker#17]
1. Pressing Ctrl+Shift+RightClick (Voronoi  Preview) in 4.0 will cause the software to crash immediately.

https://github.com/ugorek000/VoronoiLinker/assets/98995559/c83e86e5-80f5-404c-a1e3-4f881ce0ccee

![image](https://github.com/ugorek000/VoronoiLinker/assets/98995559/dfb5f04e-67be-4d00-90c1-b900ef82090d)

2.Previously, connecting from a black socket to another socket type will automatically create a socket, but I don't know why it doesn't work anymore.

https://github.com/ugorek000/VoronoiLinker/assets/98995559/a07fc6e4-8a9d-4048-82a6-1de518984004

3.Regarding the strange bug of Voronoi Repeating.
If a link has just been disconnected, the duplicate is the input socket of the disconnected link.
After using this function and then using Ctrl Z to undo, the function cannot be used anymore.

https://github.com/ugorek000/VoronoiLinker/assets/98995559/9ef982b6-1720-4a62-83b1-24a6eedb6889

I don't know if you have already discovered this. I hope you can understand what I mean.
I really like the new features of plugins.Thank you very much for your efforts.
I'm sorry for so many requests. I hope you don't hate this.

**Comment by ugorek000** [comment]
1. All the problems with (not yet released) Blender 4.0 can be explained by this:
![image](https://github.com/ugorek000/VoronoiLinker/assets/120259754/82ad8acc-86c0-4f2b-b856-9aa57dad6c90)

2. Since Blender 3.4, interfaces via api were no longer auto-created. I had to do this manually. But my method was terribly crooked, so I turned it off. I'm waiting for Blender 4.0 to make this a competent implementation again.

3. Thank you, very unexpected. I don’t know how to fix it, so I just drowned out the problem.
